### ISSUE TITLE
target-language attribute missing

### ISSUE THREAD

**Issue by joeyg** [mozilla-l10n/lockwiseios-l10n#5]
I am updating the [import scripts](https://github.com/mozilla-mobile/ios-l10n-scripts) to import lockwise translations. When testing with the german translation the file nodes do not have a `target-language` attribute. 
For example: https://github.com/mozilla-l10n/lockwiseios-l10n/blob/master/de/lockwise-ios.xliff#L3

Here is an example in firefox-ios: https://github.com/mozilla-l10n/firefoxios-l10n/blob/master/de/firefox-ios.xliff#L3

Not sure how those get added or if I should add them manually and put up a PR.

cc'ing @sashei @devinreams

**Comment by flodolo** [comment]
I don't think this is on our team to fix, Stefan is familiar with the process and tooling used to import and export.

See https://github.com/mozilla-mobile/ios-l10n-scripts/blob/master/update-xliff.py#L170-L173

**Comment by joeyg** [comment]
@flodolo great find! thanks. I have a bug somewhere in the script.

**Comment by flodolo** [comment]
To clarify, you need to run the update script once on the repo to "initialize" the new files with the correct target-language. Pontoon doesn't add that, it's the update script that does. It also adds the missing strings as untranslated (IIRC, the import would complain otherwise).

Normally, on iOS projects we would add the file from the template, and run the script to clean it up

**Comment by Pike** [comment]
I'm pretty sure that's a human bug. I copied the template verbatim, and didn't run any scripts to generate the german xliff file.

I bet using the proper tools will generate proper results.

My intent was only to test the different files and the storyboard origins of 'em.

I wouldn't be surprised if we end up resetting the repo contents here when we're ready to actually localize.
